php:
 - 7.3
env:
  global:
    - DISPLAY=:99.0
    - BROWSER_NAME="htmlunit"
    - SELENIUM_SERVER="https://selenium-release.storage.googleapis.com/3.14/selenium-server-standalone-3.14.0.jar" # Latest version including HtmlUnit
services:
 - mysql
 - xvfb
install:  
 - "composer install" 
script: phpunit --configuration phpunit.xml --coverage-text
matrix:
 allow_failures:
   - php: 7.3
   - name: 'Sauce Labs, Chrome 74, OSS protocol'
