# Required to run your project under the correct environment.
language: php
# Versions of PHP you want your project run with.
php:
 - 7.3
services:
 - mysql
install:  
 - "composer install" 
# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
before_script:
 - mkdir -p src-tests/logs/
  - mkdir -p src-tests/coverage/
  - mkdir chromedriver; CHROMEDRIVER_VERSION=$(wget -qO- "https://chromedriver.storage.googleapis.com/LATEST_RELEASE"); wget -q -t 3 https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip; unzip chromedriver_linux64 -d chromedriver
  - CHROMEDRIVER_PATH=$PWD/chromedriver/chromedriver
  - SELENIUM_JAR=$(bin/steward install --no-interaction --no-ansi $SELENIUM_VERSION)
  - java -Dwebdriver.chrome.driver="$CHROMEDRIVER_PATH" -jar $SELENIUM_JAR -log selenium-server.log &
  - until $(echo | nc localhost 4444); do sleep 1; echo Waiting for selenium-server to start...; done;
script: phpunit --configuration phpunit.xml --coverage-text
# allow_failures: Allow this build to fail under the specified environments.
# fast_finish: If your build fails do not continue trying to build, just stop.
matrix:
 allow_failures:
   - php: 7.3
 fast_finish: true
