language: php
dist: xenial

php:
 - 7.3
env:
  global:
    - DISPLAY=:99.0
    - BROWSER_NAME="turismonacionaleinternacional"
    - SELENIUM_SERVER="https://selenium-release.storage.googleapis.com/3.14/selenium-server-standalone-3.14.0.jar" # Latest version including HtmlUnit
services:
 - mysql
 - xvfb
addons:
  chrome: stable
install:  
 - "composer install" 
script: phpunit --configuration phpunit.xml --coverage-text

before_script:
- wget https://chromedriver.storage.googleapis.com/79.0.3945.36/chromedriver_linux64.zip;
- unzip chromedriver_linux64.zip;
- "wget https://selenium-release.storage.googleapis.com/3.14/selenium-server-standalone-3.14.0.jar"
- "java -Dwebdriver.chrome.driver=chromedriver -jar selenium-server-standalone-3.14.0.jar & "
-  php -S 127.0.0.1:8000 -t test/funcional/ &>>./logs/php-server.log &
- sleep 30
    
