# Required to run your project under the correct environment.
language: php
# Versions of PHP you want your project run with.
php:
 - 7.3
env:
  global:
    - DISPLAY=:99.0
    - BROWSER_NAME="htmlunit"
    - SELENIUM_SERVER="https://selenium-release.storage.googleapis.com/3.14/selenium-server-standalone-3.14.0.jar" # Latest version including HtmlUnit
services:
 - mysql
 - xvfb
install:  
 - "composer install" 
# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
before_script:
- wget http://chromedriver.storage.googleapis.com/2.0/chromedriver_win32.zip
- "wget https://selenium-release.storage.googleapis.com/3.14/selenium-server-standalone-3.14.0.jar"
- "java -jar selenium-server-standalone-3.14.0.jar > /dev/null 2>/dev/null &"
script: phpunit --configuration phpunit.xml --coverage-text
# allow_failures: Allow this build to fail under the specified environments.
# fast_finish: If your build fails do not continue trying to build, just stop.
matrix:
 allow_failures:
   - php: 7.3
   - name: 'Sauce Labs, Chrome 74, OSS protocol'
   env: SAUCELABS=1 BROWSER_NAME="chrome" VERSION="74.0" PLATFORM="Windows 10" DISABLE_W3C_PROTOCOL="1" # 74 is the last version which don't use W3C WebDriver by default
before_script:
    - php -S 127.0.0.1:8000 -t tests/functional/web/ &>>./logs/php-server.log &
    - until $(echo | nc localhost 8000); do sleep 1; echo waiting for PHP server on port 8000...; done; echo "PHP server started"