language: php
php:
 - 7.3
env:
  global:
    - DISPLAY=:99.0
    - BROWSER_NAME="turismonacionaleinternacional"
    - SELENIUM_SERVER="https://selenium-release.storage.googleapis.com/3.14/selenium-server-standalone-3.14.0.jar" # Latest version including HtmlUnit
services:
 - mysql
 - xvfb
install:  
 - "composer install" 
script: phpunit --configuration phpunit.xml --coverage-text
before_script:
    - wget https://chromedriver.storage.googleapis.com/79.0.3945.36/chromedriver_win32.zip;
    - unzip chromedriver_win32.zip;
    - "wget https://selenium-release.storage.googleapis.com/3.14/selenium-server-standalone-3.14.0.jar"
    - "java -Dwebdriver.chrome.driver=chromedriver -jar selenium-server-standalone-3.14.0.jar"
    - php -S localhost:4444 -t test/funcional/ &>>./logs/php-server.log &
    - until $(echo | nc localhost 4444); do sleep 1; echo waiting for PHP server on port 4444...; done; echo "PHP server started"
    
    
